In [1]:
import pandas as pd

columns = ['company_name', 'Scope_1', 'Scope_2', 'Scope_3', 'Total_energy_tCO2']
df = pd.DataFrame(columns = columns)

In [30]:
df.loc[len(df)] = ['Four_CS', 308.40, 290.40, 2.70, 601.50]
df.loc[len(df)] = ['BM_Fashion', 'CA', 38311, 3390, 44239]
df.loc[len(df)] = ['Clegg_Holding', 118.00, 19, 159, 296]
df.loc[len(df)] = ['TwinklUK', 5.15, 40.81, 4.93, 50.89]
df.loc[len(df)] = ['AppleBy', 884.7, 73.40, 'CA', 903.2]
df.loc[len(df)] = ['VeljiBhovan', 61.00, 213.00, 319, 'CA']
df.loc[len(df)] = ['247Recruitment', 6.86,9.74 ,63.25 , 'CA']
df.loc[len(df)] = ['Owens_Road',42779 ,640 ,'CA', 43419]
df.loc[len(df)] = ['Highwood',10.27 ,52.15 ,'CA', 247.85]
df.loc[len(df)] = ['Glasdon',48.70,12.43 ,'CA', 61.14]
df.loc[len(df)] = ['Preci_Sparks',285,1960 ,188,'CA']
df.loc[len(df)] = ['ScoffsGroup',154518,132765 ,21753+24275, 178793]
df.loc[len(df)] = ['WhatMore',218.40,4394.50 ,0.10, 4613.00]
df.loc[len(df)] = ['Whitemeadow',143.36,295.25 ,37.38, 'CA']
df.loc[len(df)] = ['Smith_Gloucester',15150502.87,15150502.87 ,1241.28, 1515050287]
df.loc[len(df)] = ['UnderwoodMeat',695.00,639.00 ,4.00, 1338.00]
df.loc[len(df)] = ['TrustPayment',8.585,23.816 ,7.857, 87.607]
df.loc[len(df)] = ['StougardenL',715.4,536.3 ,4.3, 'CA']
df.loc[len(df)] = ['NCRFinancial',248.00,565.00 ,6.00, 819.00]
df.loc[len(df)] = ['LawsonsHoldings',3757,316 ,9, 4231]
df.loc[len(df)] = ['JHSons',2279,1784 ,55, 'CA']
df.loc[len(df)] = ['BreezeMotor',43,83,0,199]
df.loc[len(df)] = ['Andrew_Bownsword','CA',265,40, 747]
df.loc[len(df)] = ['SpecialSteel',1285.50,370.30,0.20, 1656]
df.loc[len(df)] = ['ACESAC',597.59,216.40 ,0.00, 813.99]
df.loc[len(df)] = ['PukkaPies',2179.00,2140.00 ,'CA', 4231]
df.loc[len(df)] = ['HOB',240,531 ,45, 816]
df.loc[len(df)] = ['GREP1',1135,387 ,12433, 13082]
df.loc[len(df)] = ['DistinctDoors',49.10,374.00,0.20,447.70]
df.loc[len(df)] = ['ProfBeauty',297.02,278.40 ,278.40, 'CA']
df.loc[len(df)] = ['CommC',206.6,206.6 ,16.8, 'CA']
df.loc[len(df)] = ['StonegateFarmers',3077.00,58 ,58, 3193]
df.loc[len(df)] = ['Kilnbridge',1755.26,117.03 ,18.53, 1890.82]
df.loc[len(df)] = ['HotelFolk',121.74+1014.57,602.3 ,1.32, 1738.60]
df.loc[len(df)] = ['NWH_Holdings',8374,202 ,2035, 10611]
df.loc[len(df)] = ['FormulaOne',109.53,1171.20 ,'CA', 1633.55]

In [33]:
df.to_csv('estimated_results_df.csv')

In [2]:
columns = ['company_name', 'Scope_1', 'Scope_2', 'Scope_3', 'Total_energy_tCO2']
df = pd.DataFrame(columns = columns)

df.loc[len(df)] = ['Four_CS', 308.40, 290.40, 2.70, 601.50]
df.loc[len(df)] = ['BM_Fashion', 'CA', 38311, 3390, 44239]
df.loc[len(df)] = ['Clegg_Holding', 118.00, 19, 159, 296]
df.loc[len(df)] = ['TwinklUK', 5.15, 40.81, 4.93, 50.89]
df.loc[len(df)] = ['AppleBy', 884.7, 73.40, 'CA', 903.2]
df.loc[len(df)] = ['VeljiBhovan', 61.00, 213.00, 319, 'CA']
df.loc[len(df)] = ['247Recruitment', 6.86,9.74 ,63.25 , 'CA']
df.loc[len(df)] = ['Owens_Road',42779 ,640 ,'CA', 43419]
df.loc[len(df)] = ['Highwood',10.27 ,52.15 ,'CA', 247.85]
df.loc[len(df)] = ['Glasdon',48.70,12.43 ,'CA', 61.14]
df.loc[len(df)] = ['Preci_Sparks',285,1960 ,188,'CA']
df.loc[len(df)] = ['ScoffsGroup',154518,132765 ,21753+24275, 178793]
df.loc[len(df)] = ['WhatMore',218.40,4394.50 ,0.10, 4613.00]
df.loc[len(df)] = ['Whitemeadow',143.36,295.25 ,37.38, 'CA']
df.loc[len(df)] = ['Smith_Gloucester',15150502.87,15150502.87 ,1241.28, 1515050287]
df.loc[len(df)] = ['UnderwoodMeat',695.00,639.00 ,4.00, 1338.00]
df.loc[len(df)] = ['TrustPayment',8.585,23.816 ,7.857, 87.607]
df.loc[len(df)] = ['StougardenL',715.4,536.3 ,4.3, 'CA']
df.loc[len(df)] = ['NCRFinancial',248.00,565.00 ,6.00, 819.00]
df.loc[len(df)] = ['LawsonsHoldings',3757,316 ,9, 4231]
df.loc[len(df)] = ['JHSons',2279,1784 ,55, 'CA']
df.loc[len(df)] = ['BreezeMotor',43,83,0,199]
df.loc[len(df)] = ['Andrew_Bownsword','CA',265,40, 747]
df.loc[len(df)] = ['SpecialSteel',1285.50,370.30,0.20, 1656]
df.loc[len(df)] = ['ACESAC',597.59,216.40 ,0.00, 813.99]
df.loc[len(df)] = ['PukkaPies',2179.00,2140.00 ,'CA', 4231]
df.loc[len(df)] = ['HOB',240,531 ,45, 816]
df.loc[len(df)] = ['GREP1',1135,387 ,12433, 13082]
df.loc[len(df)] = ['DistinctDoors',49.10,374.00,0.20,447.70]
df.loc[len(df)] = ['ProfBeauty',297.02,278.40 ,278.40, 'CA']
df.loc[len(df)] = ['CommC',206.6,206.6 ,16.8, 'CA']
df.loc[len(df)] = ['StonegateFarmers',3077.00,58 ,58, 3193]
df.loc[len(df)] = ['Kilnbridge',1755.26,117.03 ,18.53, 1890.82]
df.loc[len(df)] = ['HotelFolk',121.74+1014.57,602.3 ,1.32, 1738.60]
df.loc[len(df)] = ['NWH_Holdings',8374,202 ,2035, 10611]
df.loc[len(df)] = ['FormulaOne',109.53,1171.20 ,'CA', 1633.55]

predicted_df = df

In [3]:
predicted_df

        company_name      Scope_1       Scope_2  Scope_3 Total_energy_tCO2
0            Four_CS        308.4  2.904000e+02      2.7             601.5
1         BM_Fashion           CA  3.831100e+04   3390.0           44239.0
2      Clegg_Holding        118.0  1.900000e+01    159.0             296.0
3           TwinklUK         5.15  4.081000e+01     4.93             50.89
4            AppleBy        884.7  7.340000e+01       CA             903.2
5        VeljiBhovan         61.0  2.130000e+02      319                CA
6     247Recruitment         6.86  9.740000e+00    63.25                CA
7         Owens_Road        42779  6.400000e+02       CA             43419
8           Highwood        10.27  5.215000e+01       CA            247.85
9            Glasdon         48.7  1.243000e+01       CA             61.14
10      Preci_Sparks          285  1.960000e+03      188                CA
11       ScoffsGroup       154518  1.327650e+05    46028            178793
12          WhatMore        218.4  4.394500e+03      0.1            4613.0
13       Whitemeadow       143.36  2.952500e+02    37.38                CA
14  Smith_Gloucester  15150502.87  1.515050e+07  1241.28        1515050287
15     UnderwoodMeat        695.0  6.390000e+02      4.0            1338.0
16      TrustPayment        8.585  2.381600e+01    7.857            87.607
17       StougardenL        715.4  5.363000e+02      4.3                CA
18      NCRFinancial        248.0  5.650000e+02      6.0             819.0
19   LawsonsHoldings         3757  3.160000e+02        9              4231
20            JHSons         2279  1.784000e+03       55                CA
21       BreezeMotor           43  8.300000e+01        0               199
22  Andrew_Bownsword           CA  2.650000e+02       40               747
23      SpecialSteel       1285.5  3.703000e+02      0.2              1656
24            ACESAC       597.59  2.164000e+02      0.0            813.99
25         PukkaPies       2179.0  2.140000e+03       CA              4231
26               HOB          240  5.310000e+02       45               816
27             GREP1         1135  3.870000e+02    12433             13082
28     DistinctDoors         49.1  3.740000e+02      0.2             447.7
29        ProfBeauty       297.02  2.784000e+02    278.4                CA
30             CommC        206.6  2.066000e+02     16.8                CA
31  StonegateFarmers       3077.0  5.800000e+01       58              3193
32        Kilnbridge      1755.26  1.170300e+02    18.53           1890.82
33         HotelFolk      1136.31  6.023000e+02     1.32            1738.6
34      NWH_Holdings         8374  2.020000e+02     2035             10611
35        FormulaOne       109.53  1.171200e+03       CA           1633.55

In [4]:
columns = ['company_name', 'Scope_1', 'Scope_2', 'Scope_3', 'Total_energy_tCO2']
df = pd.DataFrame(columns = columns)

df.loc[len(df)] = ['Four_CS', 308.40, 290.40, 2.70, 601.50]
df.loc[len(df)] = ['BM_Fashion', 2.50, 37.71,3.34 , 43.54]
df.loc[len(df)] = ['Clegg_Holding', 118.00, 19, 159, 296]
df.loc[len(df)] = ['TwinklUK', 5.15, 40.81, 4.93, 50.89]
df.loc[len(df)] = ['AppleBy', 884.7, 73.40, 'CA', 903.2]
df.loc[len(df)] = ['VeljiBhovan', 61.00, 213.00, 319, 593]
df.loc[len(df)] = ['247Recruitment', 6.86,9.74 ,63.25 , 79.85]
df.loc[len(df)] = ['Owens_Road',42779 ,640 ,0, 43419]
df.loc[len(df)] = ['Highwood',10.27 ,52.15 ,'CA', 247.85]
df.loc[len(df)] = ['Glasdon',48.70,12.43 ,0.01, 61.14]
df.loc[len(df)] = ['Preci_Sparks',285,1960 ,188,2433]
df.loc[len(df)] = ['ScoffsGroup','CA',132765 ,21753+24275, 178793]
df.loc[len(df)] = ['WhatMore',218.40,4394.50 ,0.10, 4613.00]
df.loc[len(df)] = ['Whitemeadow',1081.50,295.25 ,37.38, 1414.13]
df.loc[len(df)] = ['Smith_Gloucester',13011.5,210.14 ,14.41, 13236.06]
df.loc[len(df)] = ['UnderwoodMeat',695.00,639.00 ,4.00, 1338.00]
df.loc[len(df)] = ['TrustPayment',8.585,23.816 ,7.891, 40.292]
df.loc[len(df)] = ['StougardenL',375.8,536.3 ,3.1,915.2 ]
df.loc[len(df)] = ['NCRFinancial',248.00,565.00 ,6.00, 819.00]
df.loc[len(df)] = ['LawsonsHoldings',3757,316 ,9, 4231]
df.loc[len(df)] = ['JHSons',2279,1784 ,55, 4118]
df.loc[len(df)] = ['BreezeMotor',43,83,3,199]
df.loc[len(df)] = ['Andrew_Bownsword',442,265,40, 747]
df.loc[len(df)] = ['SpecialSteel',1285.50,370.30,0.20, 1656]
df.loc[len(df)] = ['ACESAC',597.59,216.40 ,0.00, 813.99]
df.loc[len(df)] = ['PukkaPies',2526.00,2140.00 ,4, 'CA']
df.loc[len(df)] = ['HOB',240,531 ,45, 816]
df.loc[len(df)] = ['GREP1',262,387 ,12433, 13082]
df.loc[len(df)] = ['DistinctDoors',73.50,374.00,0.20,447.70]
df.loc[len(df)] = ['ProfBeauty',297.02,278.40 ,'CA',575.42]
df.loc[len(df)] = ['CommC',206.6,67.1,16.8, 290.5]
df.loc[len(df)] = ['StonegateFarmers',3077.00,58 ,58, 3193]
df.loc[len(df)] = ['Kilnbridge',1755.26,117.03 ,18.53, 1890.82]
df.loc[len(df)] = ['HotelFolk',121.74+1014.57,602.3 ,'CA', 1738.60]
df.loc[len(df)] = ['NWH_Holdings',8374,202 ,2035, 10611]
df.loc[len(df)] = ['FormulaOne',109.53+352.82,1171.20 ,'CA', 1633.55]

actual_df = df

In [5]:
actual_df

        company_name  Scope_1     Scope_2 Scope_3 Total_energy_tCO2
0            Four_CS    308.4     290.400     2.7             601.5
1         BM_Fashion      2.5      37.710    3.34             43.54
2      Clegg_Holding    118.0      19.000   159.0             296.0
3           TwinklUK     5.15      40.810    4.93             50.89
4            AppleBy    884.7      73.400      CA             903.2
5        VeljiBhovan     61.0     213.000     319             593.0
6     247Recruitment     6.86       9.740   63.25             79.85
7         Owens_Road  42779.0     640.000       0           43419.0
8           Highwood    10.27      52.150      CA            247.85
9            Glasdon     48.7      12.430    0.01             61.14
10      Preci_Sparks    285.0    1960.000     188            2433.0
11       ScoffsGroup       CA  132765.000   46028          178793.0
12          WhatMore    218.4    4394.500     0.1            4613.0
13       Whitemeadow   1081.5     295.250   37.38           1414.13
14  Smith_Gloucester  13011.5     210.140   14.41          13236.06
15     UnderwoodMeat    695.0     639.000     4.0            1338.0
16      TrustPayment    8.585      23.816   7.891            40.292
17       StougardenL    375.8     536.300     3.1             915.2
18      NCRFinancial    248.0     565.000     6.0             819.0
19   LawsonsHoldings     3757     316.000       9            4231.0
20            JHSons     2279    1784.000      55            4118.0
21       BreezeMotor       43      83.000       3             199.0
22  Andrew_Bownsword      442     265.000      40             747.0
23      SpecialSteel   1285.5     370.300     0.2            1656.0
24            ACESAC   597.59     216.400     0.0            813.99
25         PukkaPies   2526.0    2140.000       4                CA
26               HOB      240     531.000      45               816
27             GREP1      262     387.000   12433             13082
28     DistinctDoors     73.5     374.000     0.2             447.7
29        ProfBeauty   297.02     278.400      CA            575.42
30             CommC    206.6      67.100    16.8             290.5
31  StonegateFarmers   3077.0      58.000      58              3193
32        Kilnbridge  1755.26     117.030   18.53           1890.82
33         HotelFolk  1136.31     602.300      CA            1738.6
34      NWH_Holdings     8374     202.000    2035             10611
35        FormulaOne   462.35    1171.200      CA           1633.55

In [6]:
actual_df = actual_df.applymap(lambda x: '{:.2f}'.format(x) if isinstance(x,int) else x)
predicted_df = predicted_df.applymap(lambda x: '{:.2f}'.format(x) if isinstance(x,int) else x)

/var/tmp/ipykernel_99798/726822940.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  actual_df = actual_df.applymap(lambda x: '{:.2f}'.format(x) if isinstance(x,int) else x)
/var/tmp/ipykernel_99798/726822940.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  predicted_df = predicted_df.applymap(lambda x: '{:.2f}'.format(x) if isinstance(x,int) else x)

In [7]:
%pip install --upgrade pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from IPython.display import HTML
comparison_result = (actual_df.iloc[:,1:] == predicted_df.iloc[:,1:])

total = comparison_result.size
correct = comparison_result.sum().sum()
accuracy = correct/total

color_map = comparison_result.apply(lambda x: 'background-color: green' if x.all() else 'background-color: red')

print(actual_df)

print('\n Predicted DataFrame (Highlighted rows indicate mismatches):')
predicted_df_styled = predicted_df.style.apply(lambda _: color_map, axis=None)
html = predicted_df_styled.render()
display(HTML(html))

print(f'\nOverall Accuracy: {accuracy:.2f}')

        company_name  Scope_1     Scope_2   Scope_3 Total_energy_tCO2
0            Four_CS    308.4     290.400       2.7             601.5
1         BM_Fashion      2.5      37.710      3.34             43.54
2      Clegg_Holding    118.0      19.000     159.0             296.0
3           TwinklUK     5.15      40.810      4.93             50.89
4            AppleBy    884.7      73.400        CA             903.2
5        VeljiBhovan     61.0     213.000    319.00             593.0
6     247Recruitment     6.86       9.740     63.25             79.85
7         Owens_Road  42779.0     640.000      0.00           43419.0
8           Highwood    10.27      52.150        CA            247.85
9            Glasdon     48.7      12.430      0.01             61.14
10      Preci_Sparks    285.0    1960.000    188.00            2433.0
11       ScoffsGroup       CA  132765.000  46028.00          178793.0
12          WhatMore    218.4    4394.500       0.1            4613.0
13       Whitemeadow   1081.5     295.250     37.38           1414.13
14  Smith_Gloucester  13011.5     210.140     14.41          13236.06
15     UnderwoodMeat    695.0     639.000       4.0            1338.0
16      TrustPayment    8.585      23.816     7.891            40.292
17       StougardenL    375.8     536.300       3.1             915.2
18      NCRFinancial    248.0     565.000       6.0             819.0
19   LawsonsHoldings  3757.00     316.000      9.00            4231.0
20            JHSons  2279.00    1784.000     55.00            4118.0
21       BreezeMotor    43.00      83.000      3.00             199.0
22  Andrew_Bownsword   442.00     265.000     40.00             747.0
23      SpecialSteel   1285.5     370.300       0.2            1656.0
24            ACESAC   597.59     216.400       0.0            813.99
25         PukkaPies   2526.0    2140.000      4.00                CA
26               HOB   240.00     531.000     45.00            816.00
27             GREP1   262.00     387.000  12433.00          13082.00
28     DistinctDoors     73.5     374.000       0.2             447.7
29        ProfBeauty   297.02     278.400        CA            575.42
30             CommC    206.6      67.100      16.8             290.5
31  StonegateFarmers   3077.0      58.000     58.00           3193.00
32        Kilnbridge  1755.26     117.030     18.53           1890.82
33         HotelFolk  1136.31     602.300        CA            1738.6
34      NWH_Holdings  8374.00     202.000   2035.00          10611.00
35        FormulaOne   462.35    1171.200        CA           1633.55

 Predicted DataFrame (Highlighted rows indicate mismatches):

AttributeError: 'Styler' object has no attribute 'render'